### ISSUE TITLE
Manga not found.

### ISSUE THREAD

**Issue by kou9221** [MisaghM/Tachi-Local-Details#1]
Whenever i choose a number for the manga entry it says **Manga not found.**. Can you please explain to me what ive missed to do? Cause i already read the readme. Thanks!

**Comment by MisaghM** [comment]
Sorry for the inconvenience, I was not available in the past month.
The link handler didn't work because MangaUpdates had made some changes to their website.
It should be fixed now.

**Comment by kou9221** [comment]
> Sorry for the inconvenience, I was not available in the past month.
> The link handler didn't work because MangaUpdates had made some changes to their website.
> It should be fixed now.

Thanks for update!
